name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/x0rw/restrict-ci:latest
      options: --cap-add=SYS_ADMIN --security-opt seccomp=unconfined

    steps:
      - uses: actions/checkout@v4

      - name: Set Rust stable toolchain
        run: rustup default stable
        
      - name: Copy project files
        run: cp -r . /home/runner/project

      - name: Set working directory
        working-directory: /home/runner/project
        run: echo "Working in /home/runner/project"

      - name: Build
        working-directory: /home/runner/project
        run: cargo build --verbose

      - name: Run tests
        working-directory: /home/runner/project
        run: cargo test --verbose
