name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/x0rw/restrict-ci:latest
      options: >-
        --cap-add=SYS_ADMIN
        --security-opt seccomp=unconfined
        --user 1001:1001

    steps:
      - name: Checkout code into project dir
        uses: actions/checkout@v4
        with:
          path: /home/runner/project

      - name: Fix workspace permissions
        run: sudo chown -R runner:runner /home/runner/project

      - name: Set Rust stable toolchain
        run: rustup default stable

      - name: Build & Test
        run: |
          cd /home/runner/project
          cargo build --verbose
          cargo test  --verbose
